### ISSUE TITLE
Comments in Ast

### ISSUE THREAD

**Issue by UliPlabst** [microsoft/powerquery-parser#145]
Is there a reason why the comments are not part of the parsed Ast but just flattened in the lexer snapshot? I'm building a m language autoformatter that uses your parser but at the moment I throw away all comments because it's very hard to remap the flattened comments to the Ast nodes. I think making the comments part of the ast would be the straightforward solution.

**Comment by JordanBoltonMN** [comment]
Parsers in general don't care about comments since they don't change the behavior of code. They end up getting ignored during tokenization as whitespace, or dropped/ignored during parsing.

One way you can do comment mapping is to do a `Traverse.tryTraverse` (or tryTraverseAst depending on your needs) using DFS. Make your visitNode function check if the node is a leaf node and `node.codeUnit > latestUnmappedComment`.

We're soon planning on release a new VSCode extension for Power Query. It will include a code formatter with it. Would you have interest in seeing it as a separate package, eg. `@microsoft/powerquery-format`?

**Comment by UliPlabst** [comment]
Thanks for the recommendation, I tried to traverse the Ast and map the comments to the most latest node that they occur behind and it worked. It might not be perfect but I think it's sufficient right now. 
It would be awesome if you made a separate formatter package. Is there somewhere, where I can subscribe to see news regarding the formatter or the vscode extension?

**Comment by bgribaudo** [comment]
I second the motion for a separate code formatting package.

Oh, the vscode extension sounds most interesting! I was thinking the other day about using this module to build one but sounds like you already have that well under way.... :-)

**Comment by JordanBoltonMN** [comment]
For now releasing a separate package isn't on our road map but making it easier to consume from the upcoming VSCode extension repository will be on my TODO list.

We don't have any feed regarding the extension. The MVP is mostly done and we're working on approval for release, so I can accurately say it's coming out soon-ish.

**Comment by bgribaudo** [comment]
Looking forward to it, @JordanBoltonMN!
