### ISSUE TITLE
[BUG] Parser error on record type definition - Did you leave a dangling comma?

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#244]
```
section Connector;

[DataSource.Kind="Test", Publish="Test.Publish"]
shared Test.Contents = Value.ReplaceType(TestImpl, TestType);

TestType = type function (
        param as (type text meta [
            Documentation.FieldCaption = "Param"
        ]),
        optional options as (type nullable [])
    ) as table meta [
        Documentation.Name = "Test Connector"
    ];

 TestImpl = (param as text) as table => ...;
```

Parser syntax error at [10,44] - the open bracket in `(type nullable [])`

[10, 44] Did you leave a dangling comma?

![image](https://user-images.githubusercontent.com/5509937/109230659-35b6c380-7793-11eb-8807-adffd1bf8402.png)

I feel like this might be an actual error, but it doesn't seem to cause an error in Power Query / Visual Studio.

**Comment by JordanBoltonMN** [comment]
It repros differently since the bug was added. It now parses fine, but then throws an error during validation. This is because according to the spec a `parameter-type` boils down to `as nullable-primitive-type`, and a `parenthesized-expression` obviously isn't a primitive type. Why the change in behavior? At some point the TypeScript parser was changed to match the behavior of the C# parser where it "incorrectly" allowed the parsing of parenthesized expressions in situations like this. The problem is that the type checking needs to be updated to support that "incorrect" behavior.

**Comment by JordanBoltonMN** [comment]
No longer repros.
