### ISSUE TITLE
comma before in should return error at the comma, not the in

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#47]
statement: `let a = 1, in a`

Error via M engine is reported as `A comma cannot precede an In`, with the error range set to the comma. 

powerquery-parser message is:

`Expected to find a Identifier on line 1, column 12, but a KeywordIn was found instead.`

**Comment by JordanBoltonMN** [comment]
The error reporting is very naive. In this case it's expecting another `key = value` pair, and since the key isn't an identifier it throws the error seen. This is true for anything that follows a comma separated list.

On the top of my head these are the places that need fixing: list-expression, list-type, record-expression, record-type, let-expression, function-expression, function-type.

**Comment by JordanBoltonMN** [comment]
Resolved with #49.
