### ISSUE TITLE
Parser error for column names with .

### ISSUE THREAD

**Issue by mattmasson** [microsoft/powerquery-parser#78]
```powerquery
let
    t = #table({"Column.1"}, {}),
    a = Table.AddColumn(t, "Addition", each [Timestamp.1] + 1, type number)
in
    a
```

Results in parser error:

`Expected to find a RightBracket on line 3, column 55, but a NumericLiteral was found instead.`

**Comment by JordanBoltonMN** [comment]
The issue is with parsing `Timestamp.1`. I made a TODO a while ago for improving the parsing of generalized-identifier. It's pretty hacky ATM.

However, in this specific case I don't `Timestamp.1` is valid M code. It's a generalized-identifier, which should parse as the following:

* generalized-identifier
    * generalized-identifier-part
        * generalized-identifier-segment
            * keyword-or-identifier dot-character keyword-or-identifier
                * keyword-or-identifier -> 'Timestamp'
                * dot-character -> '.'
                * keyword-or-identifier -> fails as it's neither letter-character or underscore-character

What ends up happening is "Timestamp.1" ends up being parsed as a identifier token ("Timestamp") and a numeric token ".1"

As for a fix there are a couple options I can think of. I have a helper function called 'isOnGeneralizedIdentifierToken' where I could add a case for numeric literals. A broader fix would be closer to the C# parser where it basically consumes tokens until a right bracket is reached.

Thoughts?

**Comment by mattmasson** [comment]
I'd err on the side of whatever the C# parser does. We're trying to avoid issues where something works fine in one Power Query experience, but fails in another.

**Comment by mattmasson** [comment]
I have a similar error with one of the existing connectors: 

`SweetIQ.52weeksContents`

Expected to find a Equal on line 250, column 8, but a NumericLiteral was found instead.

**Comment by JordanBoltonMN** [comment]
I agree to the approach of matching the C# parser. The fix is easy, it'll just be 'keep eating tokens until a right bracket is encountered. I'll fix it once I get the autocomplete changes in.

It's the exact same issue in fact. Once a period is encountered the spec says to start matching a C style name, meaning underscore or alpha. Digits are not allowed.
